/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVolunteerBadge } from "./IVolunteerBadge";
export type { VolunteerProof } from "./VolunteerProof";
