/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVolunteerBadge__factory } from "./IVolunteerBadge__factory";
export { VolunteerProof__factory } from "./VolunteerProof__factory";
