/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVolunteerBadge,
  IVolunteerBadgeInterface,
} from "../../../contracts/VolunteerProof.sol/IVolunteerBadge";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint8",
        name: "level",
        type: "uint8",
      },
    ],
    name: "mintIfHigherLevel",
    outputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IVolunteerBadge__factory {
  static readonly abi = _abi;
  static createInterface(): IVolunteerBadgeInterface {
    return new Interface(_abi) as IVolunteerBadgeInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVolunteerBadge {
    return new Contract(address, _abi, runner) as unknown as IVolunteerBadge;
  }
}
