/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as volunteerProofSol from "./VolunteerProof.sol";
export type { volunteerProofSol };
export type { VolunteerBadge } from "./VolunteerBadge";
export type { VolunteerComment } from "./VolunteerComment";
export type { VolunteerLike } from "./VolunteerLike";
