/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as volunteerProofSol from "./VolunteerProof.sol";
export { VolunteerBadge__factory } from "./VolunteerBadge__factory";
export { VolunteerComment__factory } from "./VolunteerComment__factory";
export { VolunteerLike__factory } from "./VolunteerLike__factory";
